# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_test1.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1186, 632)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1090, 12, 75, 41))
        self.pushButton.setObjectName("pushButton")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1071, 581))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView_LB = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graphicsView_LB.setObjectName("graphicsView_LB")
        self.gridLayout.addWidget(self.graphicsView_LB, 2, 0, 1, 1)
        self.graphicsView_LT = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graphicsView_LT.setObjectName("graphicsView_LT")
        self.gridLayout.addWidget(self.graphicsView_LT, 1, 0, 1, 1)
        self.graphicsView_RT = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graphicsView_RT.setObjectName("graphicsView_RT")
        self.gridLayout.addWidget(self.graphicsView_RT, 1, 1, 1, 1)
        self.graphicsView_RB = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graphicsView_RB.setObjectName("graphicsView_RB")
        self.gridLayout.addWidget(self.graphicsView_RB, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1186, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
